[auth]
password = "ClimatScolaire@LFIAM_2025!"

[auth.users]
"celine.rouquet@mlfmonde.org " = "Céline"
"jean-louis.bihry@mlfmonde.org " ="Jean-Louis"
"pascal.roques@mlfmonde.org" = "Pascal"
"mathieu.bartozzi@mlfmonde.org" = "Mathieu"
